// Generated by Lezer from the SDL grammar
import * as TokenTypeId from "../../lezer/parser.terms.ts";
import { InternalParseError } from "../../parse-error.ts";

export const binaryOperatorTypes: number[] = [];
export const postfixOperatorTypes: number[] = [];
export const unaryOperatorTypes: number[] = [];
export const numberLiteralTypes: number[] = [];
export const expressionTypes: number[] = [];
export const statementTypes: number[] = [];

/**
 * Map parsed token type ID to AST token type enum.
 */
Object.values(TokenTypeId).forEach((tokenTypeId) => {
  switch (tokenTypeId) {
    case TokenTypeId.Multiplication:
    case TokenTypeId.Division:
    case TokenTypeId.Modulus:
    case TokenTypeId.Addition:
    case TokenTypeId.Subtraction:
    case TokenTypeId.BitwiseShiftLeft:
    case TokenTypeId.BitwiseShiftRight:
    case TokenTypeId.RelationalLessThan:
    case TokenTypeId.RelationalLessThanOrEqual:
    case TokenTypeId.RelationalGreaterThan:
    case TokenTypeId.RelationalGreaterThanOrEqual:
    case TokenTypeId.RelationalEqual:
    case TokenTypeId.RelationalNotEqual:
    case TokenTypeId.BitwiseAnd:
    case TokenTypeId.BitwiseOr:
    case TokenTypeId.LogicalAnd:
    case TokenTypeId.LogicalOr:
      binaryOperatorTypes.push(tokenTypeId);
      break;
    case TokenTypeId.PostfixIncrement:
    case TokenTypeId.PostfixDecrement:
      postfixOperatorTypes.push(tokenTypeId);
      break;
    case TokenTypeId.UnaryPlus:
    case TokenTypeId.UnaryNegation:
      unaryOperatorTypes.push(tokenTypeId);
      break;
    case TokenTypeId.BinaryLiteral:
    case TokenTypeId.HexadecimalLiteral:
    case TokenTypeId.MultipleCharacterLiteral:
    case TokenTypeId.IntegerLiteral:
    case TokenTypeId.DecimalLiteral:
    case TokenTypeId.FloatingPointLiteral:
      numberLiteralTypes.push(tokenTypeId);
      break;
    case TokenTypeId.UnaryExpression:
    case TokenTypeId.BinaryExpression:
      expressionTypes.push(tokenTypeId);
      break;
    case TokenTypeId.CompoundStatement:
    case TokenTypeId.IfStatement:
    case TokenTypeId.SwitchStatement:
    case TokenTypeId.ForStatement:
    case TokenTypeId.DoStatement:
    case TokenTypeId.WhileStatement:
    case TokenTypeId.ExpressionStatement:
    case TokenTypeId.ElementaryTypeDefinition:
    case TokenTypeId.MapDefinition:
    case TokenTypeId.ClassDefinition:
    case TokenTypeId.StringDefinition:
    case TokenTypeId.ArrayDefinition:
    case TokenTypeId.ComputedElementaryTypeDefinition:
    case TokenTypeId.ComputedArrayDefinition:
      statementTypes.push(tokenTypeId);
      break;

    // Not currently mapped for completion rules
    case TokenTypeId.AlignedModifier:
    case TokenTypeId.AggregateOutputValue:
    case TokenTypeId.ClassDeclaration:
    case TokenTypeId.MapDeclaration:
    case TokenTypeId.AssignmentExpression:
    case TokenTypeId.LengthofExpression:
    case TokenTypeId.ArrayElementAccess:
    case TokenTypeId.Base64StringLiteral:
    case TokenTypeId.UtfStringLiteral:
    case TokenTypeId.BitModifier:
    case TokenTypeId.CaseClause:
    case TokenTypeId.ClassId:
    case TokenTypeId.ClassIdRange:
    case TokenTypeId.ExtendedClassIdRange:
    case TokenTypeId.ClassMemberAccess:
    case TokenTypeId.DefaultClause:
    case TokenTypeId.ElementaryType:
    case TokenTypeId.ElementaryTypeOutputValue:
    case TokenTypeId.ExpandableModifier:
    case TokenTypeId.ExplicitArrayDimension:
    case TokenTypeId.ImplicitArrayDimension:
    case TokenTypeId.PartialArrayDimension:
    case TokenTypeId.ExtendsModifier:
    case TokenTypeId.LengthAttribute:
    case TokenTypeId.MapEntry:
    case TokenTypeId.Parameter:
    case TokenTypeId.ParameterList:
    case TokenTypeId.ParameterValueList:
    case TokenTypeId.Specification:
    case TokenTypeId.AlignmentBitCount8:
    case TokenTypeId.AlignmentBitCount16:
    case TokenTypeId.AlignmentBitCount32:
    case TokenTypeId.AlignmentBitCount64:
    case TokenTypeId.AlignmentBitCount128:
    case TokenTypeId.Base64StringLiteralCharacters:
    case TokenTypeId.Identifier:
    case TokenTypeId.MultipleCharacterLiteralCharacters:
    case TokenTypeId.UtfStringLiteralCharacters:

    // Trivia
    case TokenTypeId.Comment:
    case TokenTypeId.Whitespace:

    // punctuation
    case TokenTypeId.Assignment:
    case TokenTypeId.CloseBrace:
    case TokenTypeId.CloseBracket:
    case TokenTypeId.CloseParenthesis:
    case TokenTypeId.Colon:
    case TokenTypeId.Comma:
    case TokenTypeId.DoubleQuote:
    case TokenTypeId.LookAhead:
    case TokenTypeId.OpenBrace:
    case TokenTypeId.OpenBracket:
    case TokenTypeId.OpenParenthesis:
    case TokenTypeId.Period:
    case TokenTypeId.RangeOperator:
    case TokenTypeId.Semicolon:
    case TokenTypeId.SingleQuote:
    case TokenTypeId.UtfPrefix:

    // keywords
    case TokenTypeId._break:
    case TokenTypeId._case:
    case TokenTypeId._class:
    case TokenTypeId._const:
    case TokenTypeId._default:
    case TokenTypeId._do:
    case TokenTypeId._else:
    case TokenTypeId._extends:
    case TokenTypeId._for:
    case TokenTypeId._if:
    case TokenTypeId._switch:
    case TokenTypeId._while:
    case TokenTypeId.abstract:
    case TokenTypeId.aligned:
    case TokenTypeId.base64string:
    case TokenTypeId.bit:
    case TokenTypeId.computed:
    case TokenTypeId.expandable:
    case TokenTypeId.float:
    case TokenTypeId.int:
    case TokenTypeId.legacy:
    case TokenTypeId.lengthof:
    case TokenTypeId.map:
    case TokenTypeId.reserved:
    case TokenTypeId.unsigned:
    case TokenTypeId.utf16string:
    case TokenTypeId.utf8list:
    case TokenTypeId.utf8string:
    case TokenTypeId.utfstring:
      break;
    default: {
      const exhaustiveCheck: never = tokenTypeId;
      throw new InternalParseError(
        "Unreachable code reached, tokenTypeId == " + exhaustiveCheck,
      );
    }
  }
});
