// Generated by Lezer from the SDL grammar
import * as TokenTypeId from "../../lezer/parser.terms.ts";

export const expressionTypes = [
  TokenTypeId.UnaryExpression,
  TokenTypeId.BinaryExpression,
];

export const statementTypes = [
  TokenTypeId.CompoundStatement,
  TokenTypeId.IfStatement,
  TokenTypeId.SwitchStatement,
  TokenTypeId.ForStatement,
  TokenTypeId.DoStatement,
  TokenTypeId.WhileStatement,
  TokenTypeId.ExpressionStatement,
  TokenTypeId.ElementaryTypeDefinition,
  TokenTypeId.MapDefinition,
  TokenTypeId.ClassDefinition,
  TokenTypeId.StringDefinition,
  TokenTypeId.ArrayDefinition,
  TokenTypeId.ComputedElementaryTypeDefinition,
  TokenTypeId.ComputedArrayDefinition,
];
