// Generated by Lezer from the SDL grammar
import * as TokenTypeId from "../../lezer/parser.terms.ts";

import { numberLiteralTypes } from "./abstract-types.ts";

export const aggregateOutputValueRules = [
  {
    previous: -1,
    expected: TokenTypeId.OpenBrace,
  },
  {
    previous: TokenTypeId.OpenBrace,
    expected: [
      TokenTypeId.ElementaryTypeOutputValue,
      TokenTypeId.OpenBrace,
      ...numberLiteralTypes,
    ],
  },
  {
    previous: TokenTypeId.Comma,
    expected: [
      TokenTypeId.ElementaryTypeOutputValue,
      TokenTypeId.OpenBrace,
      ...numberLiteralTypes,
    ],
  },
  {
    previous: TokenTypeId.ElementaryTypeOutputValue,
    expected: [
      TokenTypeId.Comma,
      TokenTypeId.CloseBrace,
    ],
  },
  {
    previous: TokenTypeId.CloseBrace,
    expected: [
      TokenTypeId.Comma,
      TokenTypeId.CloseBrace,
    ],
  },
  ...numberLiteralTypes.map((type) => ({
    previous: type,
    expected: [
      TokenTypeId.Comma,
      TokenTypeId.CloseBrace,
    ],
  })),
];
