// Generated by Lezer from the SDL grammar
import * as TokenTypeId from "../../lezer/parser.terms.ts";

export const arrayDefinitionRules = [
  {
    previous: -1,
    expected: [
      TokenTypeId.reserved,
      TokenTypeId.legacy,
      TokenTypeId.AlignedModifier,
      TokenTypeId.ElementaryType,
      TokenTypeId.Identifier,
    ],
  },
  {
    previous: TokenTypeId.reserved,
    expected: [
      TokenTypeId.AlignedModifier,
      TokenTypeId.ElementaryType,
      TokenTypeId.Identifier,
    ],
  },
  {
    previous: TokenTypeId.legacy,
    expected: [
      TokenTypeId.AlignedModifier,
      TokenTypeId.ElementaryType,
      TokenTypeId.Identifier,
    ],
  },
  {
    previous: TokenTypeId.AlignedModifier,
    expected: [TokenTypeId.ElementaryType, TokenTypeId.Identifier],
  },
  {
    previous: TokenTypeId.ElementaryType,
    expected: TokenTypeId.LengthAttribute,
  },
  {
    previous: TokenTypeId.LengthAttribute,
    expected: TokenTypeId.Identifier,
  },
  {
    previous: [-1, TokenTypeId.Identifier],
    expected: TokenTypeId.Identifier,
  },
  {
    previous: [TokenTypeId.reserved, TokenTypeId.Identifier],
    expected: TokenTypeId.Identifier,
  },
  {
    previous: [TokenTypeId.legacy, TokenTypeId.Identifier],
    expected: TokenTypeId.Identifier,
  },
  {
    previous: [TokenTypeId.AlignedModifier, TokenTypeId.Identifier],
    expected: TokenTypeId.Identifier,
  },
  {
    previous: [TokenTypeId.LengthAttribute, TokenTypeId.Identifier],
    expected: [
      TokenTypeId.ImplicitArrayDimension,
      TokenTypeId.ExplicitArrayDimension,
      TokenTypeId.PartialArrayDimension,
    ],
  },
  {
    previous: [TokenTypeId.Identifier, TokenTypeId.Identifier],
    expected: [
      TokenTypeId.ImplicitArrayDimension,
      TokenTypeId.ExplicitArrayDimension,
      TokenTypeId.PartialArrayDimension,
    ],
  },
  {
    previous: TokenTypeId.ImplicitArrayDimension,
    expected: TokenTypeId.Semicolon,
  },
  {
    previous: TokenTypeId.ExplicitArrayDimension,
    expected: [TokenTypeId.ExplicitArrayDimension, TokenTypeId.Semicolon],
  },
  {
    previous: TokenTypeId.PartialArrayDimension,
    expected: [TokenTypeId.PartialArrayDimension, TokenTypeId.Semicolon],
  },
];
