// Generated by Lezer from the SDL grammar
import * as TokenTypeId from "../../lezer/parser.terms.ts";

import { expressionTypes } from "./abstract-types.ts";

export const arrayElementAccessRules = [
  {
    previous: -1,
    expected: TokenTypeId.OpenBracket,
  },
  {
    previous: TokenTypeId.OpenBracket,
    expected: expressionTypes,
  },
  ...expressionTypes.map((expressionType) => ({
    previous: expressionType,
    expected: TokenTypeId.CloseBracket,
  })),
];
