// Generated by Lezer from the SDL grammar
import * as TokenTypeId from "../../lezer/parser.terms.ts";
import { expressionTypes } from "./abstractTypes.ts";

export const arrayElementAccessRules = [
  {
    previous: -1,
    expected: TokenTypeId.OpenBracket,
  },
  {
    previous: TokenTypeId.OpenBracket,
    expected: expressionTypes,
  },
  {
    previous: TokenTypeId.UnaryExpression,
    expected: TokenTypeId.CloseBracket,
  },
  {
    previous: TokenTypeId.BinaryExpression,
    expected: TokenTypeId.CloseBracket,
  },
];
