// Generated by Lezer from the SDL grammar
import * as TokenTypeId from "../../lezer/parser.terms.ts";

import { expressionTypes } from "./abstract-types.ts";

export const assignmentExpressionRules = [
  {
    previous: -1,
    expected: expressionTypes,
  },
  ...expressionTypes.map((expressionType) => ({
    previous: expressionType,
    expected: TokenTypeId.Assignment,
  })),
  {
    previous: TokenTypeId.Assignment,
    expected: expressionTypes,
  },
];
