import { binaryOperatorTypes, expressionTypes } from "./abstract-types.ts";

// Generated by Lezer from the SDL grammar
import * as TokenTypeId from "../../lezer/parser.terms.ts";

export const binaryExpressionRules = [
  {
    previous: -1,
    expected: TokenTypeId.UnaryExpression,
  },
  ...expressionTypes.map((type) => {
    return {
      previous: type,
      expected: binaryOperatorTypes,
    };
  }),
  ...binaryOperatorTypes.map((type) => {
    return {
      previous: type,
      expected: expressionTypes,
    };
  }),
];
