// Generated by Lezer from the SDL grammar
import * as TokenTypeId from "../../lezer/parser.terms.ts";

import { numberLiteralTypes, statementTypes } from "./abstract-types.ts";

export const caseClauseRules = [
  {
    previous: -1,
    expected: TokenTypeId._case,
  },
  {
    previous: TokenTypeId._case,
    expected: numberLiteralTypes,
  },
  ...numberLiteralTypes.map((type) => ({
    previous: type,
    expected: TokenTypeId.Colon,
  })),
  {
    previous: TokenTypeId.Colon,
    expected: [...statementTypes, TokenTypeId.OpenBrace, TokenTypeId._break],
  },
  ...statementTypes.map((type) => ({
    previous: type,
    expected: [...statementTypes, TokenTypeId._break],
  })),
  {
    previous: TokenTypeId._break,
    expected: TokenTypeId.Semicolon,
  },
  {
    previous: TokenTypeId.OpenBrace,
    expected: statementTypes,
  },
  {
    previous: TokenTypeId.Semicolon,
    expected: TokenTypeId.CloseBrace,
  },
];
