// Generated by Lezer from the SDL grammar
import * as TokenTypeId from "../../lezer/parser.terms.ts";

import { statementTypes } from "./abstractTypes.ts";

export const classDeclarationRules = [
  {
    previous: -1,
    expected: [
      TokenTypeId.AlignedModifier,
      TokenTypeId.ExpandableModifier,
      TokenTypeId.abstract,
      TokenTypeId._class,
    ],
  },
  {
    previous: TokenTypeId.AlignedModifier,
    expected: [
      TokenTypeId.ExpandableModifier,
      TokenTypeId.abstract,
      TokenTypeId._class,
    ],
  },
  {
    previous: TokenTypeId.ExpandableModifier,
    expected: [
      TokenTypeId.abstract,
      TokenTypeId._class,
    ],
  },
  {
    previous: TokenTypeId.abstract,
    expected: TokenTypeId._class,
  },
  {
    previous: TokenTypeId._class,
    expected: TokenTypeId.Identifier,
  },
  {
    previous: TokenTypeId.Identifier,
    expected: [
      TokenTypeId.ParameterList,
      TokenTypeId.ExtendsModifier,
      TokenTypeId.BitModifier,
      TokenTypeId.OpenBrace,
    ],
  },
  {
    previous: TokenTypeId.ParameterList,
    expected: [
      TokenTypeId.ExtendsModifier,
      TokenTypeId.BitModifier,
      TokenTypeId.OpenBrace,
    ],
  },
  {
    previous: TokenTypeId.ExtendsModifier,
    expected: [
      TokenTypeId.BitModifier,
      TokenTypeId.OpenBrace,
    ],
  },
  {
    previous: TokenTypeId.BitModifier,
    expected: TokenTypeId.OpenBrace,
  },
  {
    previous: TokenTypeId.OpenBrace,
    expected: [
      ...statementTypes,
      TokenTypeId.CloseBrace,
    ],
  },
  ...statementTypes.map((type) => ({
    previous: type,
    expected: [
      ...statementTypes,
      TokenTypeId.CloseBrace,
    ],
  })),
];
