// Generated by Lezer from the SDL grammar
import * as TokenTypeId from "../../lezer/parser.terms.ts";

export const classIdRules = [
  {
    previous: -1,
    expected: TokenTypeId.IntegerLiteral,
  },
];
