// Generated by Lezer from the SDL grammar
import * as TokenTypeId from "../../lezer/parser.terms.ts";

export const classIdRangeRules = [
  {
    previous: -1,
    expected: TokenTypeId.ClassId,
  },
  {
    previous: TokenTypeId.ClassId,
    expected: TokenTypeId.RangeOperator,
  },
  {
    previous: TokenTypeId.RangeOperator,
    expected: TokenTypeId.ClassId,
  },
];
