// Generated by Lezer from the SDL grammar
import * as TokenTypeId from "../../lezer/parser.terms.ts";

export const classMemberAccessRules = [
  { previous: -1, expected: TokenTypeId.Period },
  { previous: TokenTypeId.Period, expected: TokenTypeId.Identifier },
];
