// Generated by Lezer from the SDL grammar
import * as TokenTypeId from "../../lezer/parser.terms.ts";

export const classDefinitionRules = [
  {
    previous: -1,
    expected: [
      TokenTypeId.legacy,
      TokenTypeId.Identifier,
    ],
  },
  {
    previous: TokenTypeId.legacy,
    expected: TokenTypeId.Identifier,
  },
  {
    previous: TokenTypeId.Identifier,
    expected: TokenTypeId.Identifier,
  },
  {
    previous: [TokenTypeId.Identifier, TokenTypeId.Identifier],
    expected: [TokenTypeId.ParameterValueList, TokenTypeId.Semicolon],
  },
  {
    previous: TokenTypeId.ParameterValueList,
    expected: TokenTypeId.Semicolon,
  },
];
