// Generated by Lezer from the SDL grammar
import * as TokenTypeId from "../../lezer/parser.terms.ts";

export const computedArrayDefinitionRules = [
  {
    previous: -1,
    expected: TokenTypeId.computed,
  },
  {
    previous: TokenTypeId.computed,
    expected: TokenTypeId.ElementaryType,
  },
  {
    previous: TokenTypeId.ElementaryType,
    expected: TokenTypeId.Identifier,
  },
  {
    previous: TokenTypeId.Identifier,
    expected: TokenTypeId.ExplicitArrayDimension,
  },
  {
    previous: TokenTypeId.ExplicitArrayDimension,
    expected: [TokenTypeId.ExplicitArrayDimension, TokenTypeId.Semicolon],
  },
];
