import { binaryOperatorTypes, expressionTypes } from "./abstract-types.ts";

// Generated by Lezer from the SDL grammar
import * as TokenTypeId from "../../lezer/parser.terms.ts";

export const computedElementaryTypeRules = [
  { previous: -1, expected: TokenTypeId.computed },
  {
    previous: TokenTypeId.computed,
    expected: [TokenTypeId._const, TokenTypeId.ElementaryType],
  },
  { previous: TokenTypeId._const, expected: TokenTypeId.ElementaryType },
  { previous: TokenTypeId.ElementaryType, expected: TokenTypeId.Identifier },
  // const must have an assignment
  {
    previous: [
      TokenTypeId.computed,
      TokenTypeId._const,
      TokenTypeId.ElementaryType,
      TokenTypeId.Identifier,
    ],
    expected: TokenTypeId.Assignment,
  },
  // non-const has optional assignment
  {
    previous: [
      TokenTypeId.computed,
      TokenTypeId.ElementaryType,
      TokenTypeId.Identifier,
    ],
    expected: [TokenTypeId.Assignment, TokenTypeId.Semicolon],
  },
  {
    previous: TokenTypeId.Assignment,
    expected: expressionTypes,
  },
  ...expressionTypes.map((expressionType) => ({
    previous: expressionType,
    expected: [
      TokenTypeId.Semicolon,
      ...binaryOperatorTypes,
    ],
  })),
];
