// Generated by Lezer from the SDL grammar
import * as TokenTypeId from "../../lezer/parser.terms.ts";

import { statementTypes } from "./abstractTypes.ts";

export const compoundStatementRules = [
  {
    previous: -1,
    expected: TokenTypeId.OpenBrace,
  },
  {
    previous: TokenTypeId.OpenBrace,
    expected: [
      ...statementTypes,
      TokenTypeId.CloseBrace,
    ],
  },
  ...statementTypes.map((type) => ({
    previous: type,
    expected: [
      ...statementTypes,
      TokenTypeId.CloseBrace,
    ],
  })),
];
