// Generated by Lezer from the SDL grammar
import * as TokenTypeId from "../../lezer/parser.terms.ts";

import { statementTypes } from "./abstractTypes.ts";

export const defaultClauseRules = [
  {
    previous: -1,
    expected: TokenTypeId._default,
  },
  {
    previous: TokenTypeId._default,
    expected: TokenTypeId.Colon,
  },
  {
    previous: TokenTypeId.Colon,
    expected: statementTypes,
  },
  ...statementTypes.map((statementType) => ({
    previous: statementType,
    expected: statementTypes,
  })),
];
