// Generated by Lezer from the SDL grammar
import * as TokenTypeId from "../../lezer/parser.terms.ts";

import { expressionTypes } from "./abstract-types.ts";

export const doStatementRules = [
  {
    previous: -1,
    expected: TokenTypeId._do,
  },
  {
    previous: TokenTypeId._do,
    expected: TokenTypeId.CompoundStatement,
  },
  {
    previous: TokenTypeId.CompoundStatement,
    expected: TokenTypeId._while,
  },
  {
    previous: TokenTypeId._while,
    expected: TokenTypeId.OpenParenthesis,
  },
  {
    previous: TokenTypeId.OpenParenthesis,
    expected: expressionTypes,
  },
  ...expressionTypes.map((expressionType) => ({
    previous: expressionType,
    expected: TokenTypeId.CloseParenthesis,
  })),
  {
    previous: TokenTypeId.CloseParenthesis,
    expected: TokenTypeId.Semicolon,
  },
];
