// Generated by Lezer from the SDL grammar
import * as TokenTypeId from "../../lezer/parser.terms.ts";

export const elementaryTypeRules = [
  {
    previous: -1,
    expected: [
      TokenTypeId.int,
      TokenTypeId.unsigned,
      TokenTypeId.float,
      TokenTypeId.bit,
    ],
  },
  {
    previous: TokenTypeId.unsigned,
    expected: TokenTypeId.int,
  },
];
