// Generated by Lezer from the SDL grammar
import * as TokenTypeId from "../../lezer/parser.terms.ts";

export const elementaryTypeOutputValueRules = [
  {
    previous: -1,
    expected: TokenTypeId.ElementaryType,
  },
  {
    previous: TokenTypeId.ElementaryType,
    expected: TokenTypeId.LengthAttribute,
  },
];
