// Generated by Lezer from the SDL grammar
import * as TokenTypeId from "../../lezer/parser.terms.ts";

export const expandableModifierRules = [
  {
    previous: -1,
    expected: TokenTypeId.expandable,
  },
  {
    previous: TokenTypeId.expandable,
    expected: TokenTypeId.OpenParenthesis,
  },
  {
    previous: TokenTypeId.OpenParenthesis,
    expected: TokenTypeId.IntegerLiteral,
  },
  {
    previous: TokenTypeId.IntegerLiteral,
    expected: TokenTypeId.CloseParenthesis,
  },
];
