// Generated by Lezer from the SDL grammar
import * as TokenTypeId from "../../lezer/parser.terms.ts";

import { expressionTypes } from "./abstract-types.ts";

export const expressionStatementRules = [
  {
    previous: -1,
    expected: [...expressionTypes, TokenTypeId.AssignmentExpression],
  },
  ...expressionTypes.map((expressionType) => ({
    previous: expressionType,
    expected: TokenTypeId.Semicolon,
  })),
  {
    previous: TokenTypeId.AssignmentExpression,
    expected: TokenTypeId.Semicolon,
  },
];
