// Generated by Lezer from the SDL grammar
import * as TokenTypeId from "../../lezer/parser.terms.ts";

export const extendsModifierRules = [
  {
    previous: -1,
    expected: TokenTypeId.KeywordExtends,
  },
  {
    previous: TokenTypeId.KeywordExtends,
    expected: TokenTypeId.Identifier,
  },
  {
    previous: TokenTypeId.Identifier,
    expected: TokenTypeId.ParameterValueList,
  },
];
