// Generated by Lezer from the SDL grammar
import * as TokenTypeId from "../../lezer/parser.terms.ts";

export const extendedClassIdRangeRules = [
  {
    previous: -1,
    expected: [TokenTypeId.ClassId, TokenTypeId.ClassIdRange],
  },
  {
    previous: TokenTypeId.ClassId,
    expected: TokenTypeId.Comma,
  },
  {
    previous: TokenTypeId.ClassIdRange,
    expected: TokenTypeId.Comma,
  },
];
