import {
  binaryOperatorTypes,
  expressionTypes,
  statementTypes,
} from "./abstract-types.ts";

// Generated by Lezer from the SDL grammar
import * as TokenTypeId from "../../lezer/parser.terms.ts";

export const ifStatementRules = [
  {
    previous: -1,
    expected: TokenTypeId._if,
  },
  {
    previous: TokenTypeId._if,
    expected: TokenTypeId.OpenParenthesis,
  },
  {
    previous: TokenTypeId.OpenParenthesis,
    expected: expressionTypes,
  },
  ...expressionTypes.map((expressionType) => ({
    previous: expressionType,
    expected: [
      TokenTypeId.CloseParenthesis,
      ...binaryOperatorTypes,
    ],
  })),
  {
    previous: TokenTypeId.CloseParenthesis,
    expected: statementTypes,
  },
  ...statementTypes.map((statementType) => ({
    previous: statementType,
    expected: TokenTypeId._else,
  })),
  {
    previous: TokenTypeId._else,
    expected: statementTypes,
  },
];
