// Generated by Lezer from the SDL grammar
import * as TokenTypeId from "../../lezer/parser.terms.ts";

export const implicitArrayDimensionRules = [
  {
    previous: -1,
    expected: TokenTypeId.OpenBracket,
  },
  {
    previous: TokenTypeId.OpenBracket,
    expected: [TokenTypeId.IntegerLiteral, TokenTypeId.CloseBracket],
  },
  {
    previous: [TokenTypeId.OpenBracket, TokenTypeId.IntegerLiteral],
    expected: TokenTypeId.RangeOperator,
  },
  {
    previous: [TokenTypeId.RangeOperator, TokenTypeId.IntegerLiteral],
    expected: TokenTypeId.CloseBracket,
  },
];
