// Generated by Lezer from the SDL grammar
import * as TokenTypeId from "../../lezer/parser.terms.ts";

export const mapDefinitionRules = [
  {
    previous: -1,
    expected: [
      TokenTypeId.reserved,
      TokenTypeId.legacy,
      TokenTypeId.ElementaryType,
      TokenTypeId.Identifier,
    ],
  },
  {
    previous: TokenTypeId.reserved,
    expected: [TokenTypeId.ElementaryType, TokenTypeId.Identifier],
  },
  {
    previous: TokenTypeId.legacy,
    expected: [TokenTypeId.ElementaryType, TokenTypeId.Identifier],
  },
  {
    previous: TokenTypeId.ElementaryType,
    expected: TokenTypeId.RelationalLessThan,
  },
  {
    previous: TokenTypeId.Identifier,
    expected: TokenTypeId.RelationalLessThan,
  },
  {
    previous: TokenTypeId.RelationalLessThan,
    expected: TokenTypeId.Identifier,
  },
  {
    previous: [TokenTypeId.RelationalLessThan, TokenTypeId.Identifier],
    expected: TokenTypeId.RelationalGreaterThan,
  },
  {
    previous: [TokenTypeId.Identifier, TokenTypeId.RelationalGreaterThan],
    expected: TokenTypeId.Identifier,
  },
  {
    previous: [TokenTypeId.RelationalGreaterThan, TokenTypeId.Identifier],
    expected: TokenTypeId.Semicolon,
  },
];
