// Generated by Lezer from the SDL grammar
import * as TokenTypeId from "../../lezer/parser.terms.ts";

export const mapDeclarationRules = [
  {
    previous: -1,
    expected: TokenTypeId.map,
  },
  {
    previous: TokenTypeId.map,
    expected: TokenTypeId.Identifier,
  },
  {
    previous: [TokenTypeId.map, TokenTypeId.Identifier],
    expected: TokenTypeId.OpenParenthesis,
  },
  {
    previous: TokenTypeId.OpenParenthesis,
    expected: [TokenTypeId.ElementaryType, TokenTypeId.Identifier],
  },
  {
    previous: TokenTypeId.ElementaryType,
    expected: TokenTypeId.CloseParenthesis,
  },
  {
    previous: TokenTypeId.Identifier,
    expected: TokenTypeId.CloseParenthesis,
  },
  {
    previous: TokenTypeId.CloseParenthesis,
    expected: TokenTypeId.OpenBrace,
  },
  {
    previous: TokenTypeId.OpenBrace,
    expected: TokenTypeId.MapEntry,
  },
  {
    previous: TokenTypeId.MapEntry,
    expected: [TokenTypeId.Comma, TokenTypeId.CloseBrace],
  },
  {
    previous: TokenTypeId.Comma,
    expected: TokenTypeId.MapEntry,
  },
];
