// Generated by Lezer from the SDL grammar
import * as TokenTypeId from "../../lezer/parser.terms.ts";

export const mapEntryRules = [
  {
    previous: -1,
    expected: TokenTypeId.BinaryLiteral,
  },
  {
    previous: TokenTypeId.BinaryLiteral,
    expected: TokenTypeId.Comma,
  },
  {
    previous: TokenTypeId.Comma,
    expected: TokenTypeId.AggregateOutputValue,
  },
];
