// Generated by Lezer from the SDL grammar
import * as TokenTypeId from "../../lezer/parser.terms.ts";

export const parameterListRules = [
  {
    previous: -1,
    expected: TokenTypeId.OpenParenthesis,
  },
  {
    previous: TokenTypeId.OpenParenthesis,
    expected: TokenTypeId.Parameter,
  },
  {
    previous: TokenTypeId.Parameter,
    expected: [TokenTypeId.Comma, TokenTypeId.CloseParenthesis],
  },
  {
    previous: TokenTypeId.Comma,
    expected: TokenTypeId.Parameter,
  },
];
