// Generated by Lezer from the SDL grammar
import * as TokenTypeId from "../../lezer/parser.terms.ts";
import { expressionTypes } from "./abstractTypes.ts";

export const parameterValueListRules = [
  {
    previous: TokenTypeId.OpenParenthesis,
    expected: expressionTypes,
  },
  {
    previous: TokenTypeId.Comma,
    expected: expressionTypes,
  },
  {
    previous: TokenTypeId.UnaryExpression,
    expected: [
      TokenTypeId.Comma,
      TokenTypeId.CloseParenthesis,
    ],
  },
  {
    previous: TokenTypeId.BinaryExpression,
    expected: [
      TokenTypeId.Comma,
      TokenTypeId.CloseParenthesis,
    ],
  },
];
