// Generated by Lezer from the SDL grammar
import * as TokenTypeId from "../../lezer/parser.terms.ts";

export const parameterRules = [
  {
    previous: -1,
    expected: [TokenTypeId.Identifier, TokenTypeId.ElementaryType],
  },
  {
    previous: [-1, TokenTypeId.Identifier],
    expected: TokenTypeId.Identifier,
  },
  {
    previous: TokenTypeId.ElementaryType,
    expected: TokenTypeId.Identifier,
  },
];
