import { binaryOperatorTypes, expressionTypes } from "./abstract-types.ts";

// Generated by Lezer from the SDL grammar
import * as TokenTypeId from "../../lezer/parser.terms.ts";

export const partialArrayDimensionRules = [
  {
    previous: -1,
    expected: TokenTypeId.OpenBracket,
  },
  {
    previous: [-1, TokenTypeId.OpenBracket],
    expected: TokenTypeId.OpenBracket,
  },
  {
    previous: [TokenTypeId.OpenBracket, TokenTypeId.OpenBracket],
    expected: expressionTypes,
  },
  ...expressionTypes.map((expressionType) => ({
    previous: expressionType,
    expected: [
      TokenTypeId.CloseBracket,
      ...binaryOperatorTypes,
    ],
  })),
  ...expressionTypes.map((expressionType) => ({
    previous: [expressionType, TokenTypeId.CloseBracket],
    expected: [
      TokenTypeId.CloseBracket,
      ...binaryOperatorTypes,
    ],
  })),
];
