// Generated by Lezer from the SDL grammar
import * as TokenTypeId from "../../lezer/parser.terms.ts";

export const specificationRules = [
  {
    previous: -1,
    expected: [
      TokenTypeId.ClassDeclaration,
      TokenTypeId.MapDeclaration,
      TokenTypeId.ComputedElementaryTypeDefinition,
    ],
  },
];
