// Generated by Lezer from the SDL grammar
import * as TokenTypeId from "../../lezer/parser.terms.ts";

export const stringDefinitionRules = [
  {
    previous: [
      TokenTypeId.utf8string,
      TokenTypeId.Identifier,
      TokenTypeId.Assignment,
    ],
    expected: TokenTypeId.UtfStringLiteral,
  },
  {
    previous: [
      TokenTypeId.utf16string,
      TokenTypeId.Identifier,
      TokenTypeId.Assignment,
    ],
    expected: TokenTypeId.UtfStringLiteral,
  },
  {
    previous: [
      TokenTypeId.utfstring,
      TokenTypeId.Identifier,
      TokenTypeId.Assignment,
    ],
    expected: TokenTypeId.UtfStringLiteral,
  },
  {
    previous: [
      TokenTypeId.base64string,
      TokenTypeId.Identifier,
      TokenTypeId.Assignment,
    ],
    expected: TokenTypeId.Base64StringLiteral,
  },
  {
    previous: TokenTypeId.reserved,
    expected: [
      TokenTypeId._const,
      TokenTypeId.AlignedModifier,
      TokenTypeId.utf8string,
      TokenTypeId.utf16string,
      TokenTypeId.utfstring,
      TokenTypeId.base64string,
    ],
  },
  {
    previous: TokenTypeId._const,
    expected: [
      TokenTypeId.AlignedModifier,
      TokenTypeId.utf8string,
      TokenTypeId.utf16string,
      TokenTypeId.utfstring,
      TokenTypeId.base64string,
    ],
  },
  {
    previous: TokenTypeId.AlignedModifier,
    expected: [
      TokenTypeId.utf8string,
      TokenTypeId.utf16string,
      TokenTypeId.utfstring,
      TokenTypeId.base64string,
    ],
  },
  {
    previous: [
      TokenTypeId.utf8string,
      TokenTypeId.Identifier,
    ],
    expected: TokenTypeId.Semicolon,
  },
  {
    previous: [
      TokenTypeId.utf16string,
      TokenTypeId.Identifier,
    ],
    expected: TokenTypeId.Semicolon,
  },
  {
    previous: [
      TokenTypeId.utfstring,
      TokenTypeId.Identifier,
    ],
    expected: TokenTypeId.Semicolon,
  },
  {
    previous: [
      TokenTypeId.base64string,
      TokenTypeId.Identifier,
    ],
    expected: TokenTypeId.Semicolon,
  },
  {
    previous: TokenTypeId.Base64StringLiteral,
    expected: TokenTypeId.Semicolon,
  },
  {
    previous: TokenTypeId.UtfStringLiteral,
    expected: TokenTypeId.Semicolon,
  },
];
