// Generated by Lezer from the SDL grammar
import * as TokenTypeId from "../../lezer/parser.terms.ts";

import { expressionTypes } from "./abstract-types.ts";

export const switchStatementRules = [
  {
    previous: -1,
    expected: TokenTypeId._switch,
  },
  {
    previous: TokenTypeId._switch,
    expected: TokenTypeId.OpenParenthesis,
  },
  {
    previous: TokenTypeId.OpenParenthesis,
    expected: expressionTypes,
  },
  ...expressionTypes.map((expressionType) => ({
    previous: expressionType,
    expected: TokenTypeId.CloseParenthesis,
  })),
  {
    previous: TokenTypeId.CloseParenthesis,
    expected: TokenTypeId.OpenBrace,
  },
  {
    previous: TokenTypeId.OpenBrace,
    expected: [
      TokenTypeId.CaseClause,
      TokenTypeId.DefaultClause,
      TokenTypeId.CloseBrace,
    ],
  },
  {
    previous: TokenTypeId.CaseClause,
    expected: [
      TokenTypeId.CaseClause,
      TokenTypeId.DefaultClause,
      TokenTypeId.CloseBrace,
    ],
  },
  {
    previous: TokenTypeId.DefaultClause,
    expected: TokenTypeId.CloseBrace,
  },
];
