// Generated by Lezer from the SDL grammar
import * as TokenTypeId from "../../lezer/parser.terms.ts";

import {
  expressionTypes,
  numberLiteralTypes,
  postfixOperatorTypes,
  unaryOperatorTypes,
} from "./abstract-types.ts";

export const unaryExpressionRules = [
  {
    previous: -1,
    expected: [
      ...expressionTypes,
      ...unaryOperatorTypes,
      TokenTypeId.LengthofExpression,
      TokenTypeId.Identifier,
      ...numberLiteralTypes,
      TokenTypeId.OpenParenthesis,
    ],
  },
  ...expressionTypes.map((expressionType) => ({
    previous: expressionType,
    expected: [
      TokenTypeId.ArrayElementAccess,
      TokenTypeId.ClassMemberAccess,
      ...postfixOperatorTypes,
    ],
  })),
  ...unaryOperatorTypes.map((unaryOperatorType) => ({
    previous: unaryOperatorType,
    expected: expressionTypes,
  })),
  {
    previous: TokenTypeId.OpenParenthesis,
    expected: [...expressionTypes],
  },
  ...expressionTypes.map((expressionType) => ({
    previous: expressionType,
    expected: TokenTypeId.CloseParenthesis,
  })),
];
