// Generated by Lezer from the SDL grammar
import * as TokenTypeId from "../../lezer/parser.terms.ts";

export const utfStringLiteralRules = [
  {
    previous: -1,
    expected: TokenTypeId.UtfPrefix,
  },
  {
    previous: TokenTypeId.UtfStringLiteralCharacters,
    expected: TokenTypeId.DoubleQuote,
  },
  {
    previous: TokenTypeId.DoubleQuote,
    expected: TokenTypeId.UtfPrefix,
  },
];
