import { binaryOperatorTypes, expressionTypes } from "./abstract-types.ts";

// Generated by Lezer from the SDL grammar
import * as TokenTypeId from "../../lezer/parser.terms.ts";

export const whileStatementRules = [
  {
    previous: -1,
    expected: TokenTypeId._while,
  },
  {
    previous: TokenTypeId._while,
    expected: TokenTypeId.OpenParenthesis,
  },
  {
    previous: TokenTypeId.OpenParenthesis,
    expected: expressionTypes,
  },
  {
    previous: TokenTypeId.UnaryExpression,
    expected: TokenTypeId.CloseParenthesis,
  },
  ...expressionTypes.map((expressionType) => ({
    previous: expressionType,
    expected: [
      TokenTypeId.CloseParenthesis,
      ...binaryOperatorTypes,
    ],
  })),
  {
    previous: TokenTypeId.CloseParenthesis,
    expected: TokenTypeId.CompoundStatement,
  },
];
