import { describe, test } from "bun:test";
import { testCompletionScenario } from "./test-completion-scenario.ts";

// Generated by Lezer from the SDL grammar
import * as TokenTypeId from "../../src/lezer/parser.terms.ts";

describe("getExpectedTokenTypeIds Tests", () => {
  test("Test missing length attribute", () => {
    testCompletionScenario(
      "class A { bit b; }",
      [TokenTypeId.LengthAttribute],
    );
  });

  test("Test duplicate identifier", () => {
    testCompletionScenario(
      "class A {if (f oo) {bit(8) c;}}",
      [
        TokenTypeId.Multiplication,
        TokenTypeId.Division,
        TokenTypeId.Modulus,
        TokenTypeId.Addition,
        TokenTypeId.Subtraction,
        TokenTypeId.BitwiseShiftLeft,
        TokenTypeId.BitwiseShiftRight,
        TokenTypeId.RelationalLessThan,
        TokenTypeId.RelationalLessThanOrEqual,
        TokenTypeId.RelationalGreaterThan,
        TokenTypeId.RelationalGreaterThanOrEqual,
        TokenTypeId.RelationalEqual,
        TokenTypeId.RelationalNotEqual,
        TokenTypeId.BitwiseAnd,
        TokenTypeId.BitwiseOr,
        TokenTypeId.LogicalAnd,
        TokenTypeId.LogicalOr,
      ].sort((a, b) => a - b),
    );
  });

  test("Test complex scenario", () => {
    testCompletionScenario(
      "class A {if (a b == 0b01 || c == 0b11) {bit(8) c;}}",
      [
        TokenTypeId.CloseParenthesis,
        TokenTypeId.Multiplication,
        TokenTypeId.Division,
        TokenTypeId.Modulus,
        TokenTypeId.Addition,
        TokenTypeId.Subtraction,
        TokenTypeId.BitwiseShiftLeft,
        TokenTypeId.BitwiseShiftRight,
        TokenTypeId.RelationalLessThan,
        TokenTypeId.RelationalLessThanOrEqual,
        TokenTypeId.RelationalGreaterThan,
        TokenTypeId.RelationalGreaterThanOrEqual,
        TokenTypeId.RelationalEqual,
        TokenTypeId.RelationalNotEqual,
        TokenTypeId.BitwiseAnd,
        TokenTypeId.BitwiseOr,
        TokenTypeId.LogicalAnd,
        TokenTypeId.LogicalOr,
        TokenTypeId.Semicolon,
      ].sort((a, b) => a - b),
    );
  });
});
