import { foldNodeProp } from "@codemirror/language";

// Generated by Lezer from the SDL grammar
import * as TokenTypeId from "../parser.terms.ts";

const blockStatementTokenTypeIds = new Set<number>([
  TokenTypeId.ClassDeclaration,
  TokenTypeId.MapDeclaration,
  TokenTypeId.CompoundStatement,
  TokenTypeId.SwitchStatement,
  TokenTypeId.CaseClause,
  TokenTypeId.DefaultClause,
  TokenTypeId.IfStatement,
  TokenTypeId.WhileStatement,
  TokenTypeId.DoStatement,
  TokenTypeId.ForStatement,
]);

export const foldNodePropSource = foldNodeProp.add((type) => {
  if (!blockStatementTokenTypeIds.has(type.id)) {
    return undefined;
  }
  return (tree, state) => ({
    from: state.doc.lineAt(tree.from).to,
    to: tree.to,
  });
});
