import { NodeProp, NodeType } from "@lezer/common";

// Generated by Lezer from the SDL grammar
import * as TokenTypeId from "../parser.terms.ts";

const primitiveTokenTypeIds = new Set<number>([
  TokenTypeId.BinaryLiteral,
  TokenTypeId.DecimalLiteral,
  TokenTypeId.FloatingPointLiteral,
  TokenTypeId.HexadecimalLiteral,
  TokenTypeId.Identifier,
  TokenTypeId.IntegerLiteral,
]);

export const primitiveNodeProp = new NodeProp<boolean>();

export const primitiveNodePropSource = primitiveNodeProp.add(
  (type: NodeType) => primitiveTokenTypeIds.has(type.id) ? true : undefined,
);
