import { styleTags, Tag, tags as t } from "@lezer/highlight";
import { InternalParseError } from "../../parse-error.ts";

// Generated by Lezer from the SDL grammar
import * as TokenTypeId from "../parser.terms.ts";

const tokenIdToStyleTagMapping: { [selector: string]: Tag | readonly Tag[] } =
  {};

// iterate over all TokenTypeId properties and map them to style tags
// to ensure we don't reference any that don't exist
Object.entries(TokenTypeId).forEach(([key, value]) => {
  switch (value) {
    case TokenTypeId.int:
    case TokenTypeId.unsigned:
    case TokenTypeId.float:
    case TokenTypeId.bit:
      tokenIdToStyleTagMapping[key] = t.typeName;
      break;
    case TokenTypeId.Comment:
      tokenIdToStyleTagMapping[key] = t.comment;
      break;
    case TokenTypeId.Identifier:
      tokenIdToStyleTagMapping[key] = t.variableName;
      break;
    case TokenTypeId.AlignmentBitCount8:
    case TokenTypeId.AlignmentBitCount16:
    case TokenTypeId.AlignmentBitCount32:
    case TokenTypeId.AlignmentBitCount64:
    case TokenTypeId.AlignmentBitCount128:
    case TokenTypeId.BinaryLiteral:
    case TokenTypeId.HexadecimalLiteral:
    case TokenTypeId.MultipleCharacterLiteral:
    case TokenTypeId.MultipleCharacterLiteralCharacters:
    case TokenTypeId.Base64StringLiteralCharacters:
      tokenIdToStyleTagMapping[key] = t.literal;
      break;
    case TokenTypeId.IntegerLiteral:
    case TokenTypeId.DecimalLiteral:
    case TokenTypeId.FloatingPointLiteral:
      tokenIdToStyleTagMapping[key] = t.number;
      break;
    case TokenTypeId.Base64StringLiteral:
    case TokenTypeId.UtfStringLiteral:
      tokenIdToStyleTagMapping[key] = t.string;
      break;
    case TokenTypeId._if:
    case TokenTypeId._else:
    case TokenTypeId._switch:
    case TokenTypeId._case:
    case TokenTypeId._break:
    case TokenTypeId._do:
    case TokenTypeId._while:
      tokenIdToStyleTagMapping[key] = t.controlKeyword;
      break;
    case TokenTypeId._class:
    case TokenTypeId._extends:
    case TokenTypeId._const:
    case TokenTypeId.map:
    case TokenTypeId.utf8string:
    case TokenTypeId.utf8list:
    case TokenTypeId.utfstring:
    case TokenTypeId.utf16string:
    case TokenTypeId.reserved:
    case TokenTypeId.legacy:
    case TokenTypeId.base64string:
    case TokenTypeId.aligned:
    case TokenTypeId.expandable:
    case TokenTypeId.abstract:
    case TokenTypeId.computed:
    case TokenTypeId._default:
    case TokenTypeId._for:
      tokenIdToStyleTagMapping[key] = t.keyword;
      break;
    case TokenTypeId.OpenBrace:
    case TokenTypeId.CloseBrace:
      tokenIdToStyleTagMapping[key] = t.brace;
      break;
    case TokenTypeId.CloseParenthesis:
    case TokenTypeId.OpenParenthesis:
      tokenIdToStyleTagMapping[key] = t.paren;
      break;
    case TokenTypeId.OpenBracket:
    case TokenTypeId.CloseBracket:
      tokenIdToStyleTagMapping[key] = t.squareBracket;
      break;
    case TokenTypeId.PostfixIncrement:
    case TokenTypeId.PostfixDecrement:
    case TokenTypeId.UnaryPlus:
    case TokenTypeId.UnaryNegation:
    case TokenTypeId.Multiplication:
    case TokenTypeId.Division:
    case TokenTypeId.Modulus:
    case TokenTypeId.Addition:
    case TokenTypeId.Subtraction:
      tokenIdToStyleTagMapping[key] = t.arithmeticOperator;
      break;
    case TokenTypeId.RelationalLessThan:
    case TokenTypeId.RelationalLessThanOrEqual:
    case TokenTypeId.RelationalGreaterThan:
    case TokenTypeId.RelationalGreaterThanOrEqual:
    case TokenTypeId.RelationalEqual:
    case TokenTypeId.RelationalNotEqual:
      tokenIdToStyleTagMapping[key] = t.compareOperator;
      break;
    case TokenTypeId.BitwiseShiftLeft:
    case TokenTypeId.BitwiseShiftRight:
    case TokenTypeId.BitwiseAnd:
    case TokenTypeId.BitwiseOr:
      tokenIdToStyleTagMapping[key] = t.bitwiseOperator;
      break;
    case TokenTypeId.LogicalAnd:
    case TokenTypeId.LogicalOr:
      tokenIdToStyleTagMapping[key] = t.logicOperator;
      break;
    case TokenTypeId.lengthof:
      tokenIdToStyleTagMapping[key] = t.operatorKeyword;
      break;
    case TokenTypeId.RangeOperator:
    case TokenTypeId.Assignment:
    case TokenTypeId.LookAhead:
      tokenIdToStyleTagMapping[key] = t.operator;
      break;
    case TokenTypeId.Period:
    case TokenTypeId.UtfPrefix:
    case TokenTypeId.Colon:
    case TokenTypeId.Semicolon:
    case TokenTypeId.Comma:
    case TokenTypeId.SingleQuote:
    case TokenTypeId.DoubleQuote:
      tokenIdToStyleTagMapping[key] = t.punctuation;
      break;
    case TokenTypeId.Whitespace:
    case TokenTypeId.Specification:
    case TokenTypeId.ClassDeclaration:
    case TokenTypeId.CompoundStatement:
    case TokenTypeId.IfStatement:
    case TokenTypeId.SwitchStatement:
    case TokenTypeId.CaseClause:
    case TokenTypeId.DefaultClause:
    case TokenTypeId.WhileStatement:
    case TokenTypeId.MapDeclaration:
    case TokenTypeId.AlignedModifier:
    case TokenTypeId.ExpandableModifier:
    case TokenTypeId.ParameterList:
    case TokenTypeId.Parameter:
    case TokenTypeId.ElementaryType:
    case TokenTypeId.ExtendsModifier:
    case TokenTypeId.ParameterValueList:
    case TokenTypeId.LengthofExpression:
    case TokenTypeId.BitModifier:
    case TokenTypeId.ExtendedClassIdRange:
    case TokenTypeId.ClassId:
    case TokenTypeId.ClassIdRange:
    case TokenTypeId.ForStatement:
    case TokenTypeId.AssignmentExpression:
    case TokenTypeId.ComputedElementaryTypeDefinition:
    case TokenTypeId.DoStatement:
    case TokenTypeId.ExpressionStatement:
    case TokenTypeId.ElementaryTypeDefinition:
    case TokenTypeId.MapDefinition:
    case TokenTypeId.ClassDefinition:
    case TokenTypeId.StringDefinition:
    case TokenTypeId.UtfStringLiteralCharacters:
    case TokenTypeId.ArrayDefinition:
    case TokenTypeId.ImplicitArrayDimension:
    case TokenTypeId.ExplicitArrayDimension:
    case TokenTypeId.PartialArrayDimension:
    case TokenTypeId.ComputedArrayDefinition:
    case TokenTypeId.MapEntry:
    case TokenTypeId.AggregateOutputValue:
    case TokenTypeId.ElementaryTypeOutputValue:
    case TokenTypeId.BinaryExpression:
    case TokenTypeId.UnaryExpression:
    case TokenTypeId.ArrayElementAccess:
    case TokenTypeId.ClassMemberAccess:
    case TokenTypeId.LengthAttribute:
      break;
    default: {
      const exhaustiveCheck: never = value;
      throw new InternalParseError(
        "Unreachable code reached, tokenTypeId == " + exhaustiveCheck,
      );
    }
  }
});

export const styleTagsNodePropSource = styleTags(tokenIdToStyleTagMapping);
